version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      # - /home/vagrant/app/current/:/myapp
      - .:/myapp
    ports:
    - "80:80"
    depends_on:
      - db
  # nging-proxy:
  #   image: jwilder/nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro



# version: '2'
# services:
#   nging-proxy:
#     image: jwilder/nginx-proxy
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - /var/run/docker.sock:/tmp/docker.sock:ro
#   db:
#     image: postgres
#   web:
#     build: .
#     command: bundle exec rails s -p 3000 -b '0.0.0.0'
#     volumes:
#       - /home/vagrant/app/current/:/myapp
#     ports:
#       - "80:3000"
#     depends_on:
#       - db
