---
- name: Add deployment user
  hosts: all
  sudo: yes
  tasks:
  - user: name=deployer
  - authorized_key: user=deployer key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Installing and configuring Docker
  hosts: all
  sudo: yes
  roles:
    - { role: angstwad.docker_ubuntu }
    - { role: geerlingguy.git }

- name: Clone app
  hosts: all
  become: yes
  become_user: deployer
  tasks:
    - git: repo=https://github.com/jkubacki/dockerapp.git
           dest=/home/deployer/app/current/

- name: Setup docker
  hosts: all
  sudo: yes
  tasks:
  - set_fact: compose_dir=/home/deployer/app/current/
  - file:
      path: "{{ compose_dir }}"
      state: directory

  - name: Docker compose
    docker_service:
      project_name: dockerapp
      project_src: "{{ compose_dir }}/"
    register: output

  - name: Debug
    debug: var=output
